// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvdlhrodvevgwdsneplk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZGxocm9kdmV2Z3dkc25lcGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMTY5ODQsImV4cCI6MjA3OTU5Mjk4NH0.5TsPcH00hSuYtmd3yh-Sm42Ht8W49LLVX1WrNswDPXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});